filetypes = {
    "haskell": "hs",
    "r": "r",
    "scala": "scala",
    "markdown": "md",
    "python": "py",
    "swift": "swift",
    "c#": "cs",
    "perl": "pl",
    "ruby": "rb",
    "lua": "lua",
    "vb": "cb",
    "css": "css",
    "c": "c",
    "html": "html",
    "javascript": "js",
    "php": "php",
    "java": "java",
    "bash": "sh",
    "c++": "cpp",
    "sql": "sql",
    "objective-c": "m",
}
